name: S1000 Agent Installer Package Pipeline

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'The s1000 backend tag that you would like to create a release. Ex: 1.3.0'     
        required: true    
      appEnv:
        description: 'App Environment: options (test)'     
        required: True  

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            artifact: "windows_msvc.7z",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }

    steps:       

    - name: Install Bitbuket SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
        name: id_rsa_bit
        known_hosts: ${{ secrets.KNOWN_HOSTS_BITBUCKET }}
        config: |
          Host bitbucket-git
            HostName bitbucket.org
            IdentityFile ~/.ssh/id_rsa_bit
        if_key_exists: replace

    # - name: Retrieve Repository
    #   run: |
    #     git clone git@bitbucket-git:thinkrfsoftware/s1000_backend.git
    #     cd s1000_backend
    #     git checkout ${{ github.event.inputs.releaseTag }}

    # - name: Inno-setup
    #   shell: pwsh
    #   run: |
    #     Invoke-WebRequest -OutFile inno.exe -Uri https://jrsoftware.org/download.php/is.exe
    #     Start-Process -Wait -FilePath $PWD\inno.exe -Argument "/silent" -PassThru

    - name: Boost Library
      shell: pwsh
      run: |
        Invoke-WebRequest -OutFile boost.zip -Uri https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.zip
        7z x boost.zip -oboost
        cd boost/boost_1_80_0
        .\bootstrap.bat
        .\b2

    # - name: Build Client
    #   shell: pwsh
    #   run: |
    #     cd s1000_backend
    #     cmake .
    #     CMAKE --build .
    #     dir bin/     