name: S1000 Frontend Pipeline

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'The s1000 frontend tag that you would like to create a release. Ex: 1.3.0'     
        required: true    
      appEnv:
        description: 'App Environment: options (test)'     
        required: True        

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
        name: id_rsa_bit
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host bitbucket-git
            HostName bitbucket.org
            IdentityFile ~/.ssh/id_rsa_bit
        if_key_exists: replace

    - name: Retrieve Repository
      run: |
        git clone git@bitbucket-git:thinkrfsoftware/s1000_frontend.git
        cd s1000_frontend
        git checkout ${{ github.event.inputs.releaseTag }}
    
    - name: Generate deployment package
      run: |
        cd s1000_frontend
        zip -r deploy.zip . -x '*.git*'

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: s1000-${{ github.event.inputs.appEnv }}
        environment_name: s1000-${{ github.event.inputs.appEnv }}
        version_label: ${{ github.event.inputs.releaseTag }}
        region: us-east-2
        deployment_package: s1000_frontend/deploy.zip    