#
#****************************************************************
#  Deployment
#  Code Copyright (C) 2020-2021 ThinkRF Incorporated. All Rights Reserved.
#****************************************************************
#  @file        pipeline-testAwsCredentials
#  @author      Aly Khedr
#  @brief       Pipeline to test if we can access aws from pipeline
#               Uses S3 to retreive artifacts of S3
#**************************************************************** 
#****************************************************************
#

name: S1000 AWS 
on:
  workflow_dispatch:
    inputs:        
      S1000ReleaseTag:
        description: 'The S1000 frontend and backend tag that you would like to create a release. Ex: 1.3.0'     
        required: true   
      LibtrfReleaseTag:
        description: 'The S1000 libtrf tag that you would like to create a release. Ex: 1.3.0'     
        required: true   
      ChangelogComment:
        description: 'A sentence or short paragraph describing the important changes since the last packaging'
        required: true
      Stability:
        type: choice
        description: 'The stability of the built version (based on the amount of testing)'
        options:
          - unstable
          - testing
          - stable
  
env:
  QT_VERSION: '6.5.3'
  TAG_VERSION: ${{ github.event.inputs.S1000ReleaseTag }}

jobs:
  windows_build:
    name: "Windows Build"
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Print Release Version
        run: |
          echo "Backend Release ${{ github.event.inputs.S1000ReleaseTag }}"
          echo "Frontend Release ${{ github.event.inputs.S1000ReleaseTag }}"
  

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLIENT_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CLIENT_SECRET }}
          aws-region: us-east-2

      - name: Retrieve libtrf Repository
        run: |
          aws s3 cp s3://thinkrf-component-libtrf-library/${{ github.event.inputs.LibtrfReleaseTag }}/libtrf.h 
          aws s3 cp s3://thinkrf-component-libtrf-library/${{ github.event.inputs.LibtrfReleaseTag }}/x64/libtrf.lib 
          aws s3 cp s3://thinkrf-component-libtrf-library/${{ github.event.inputs.LibtrfReleaseTag }}/x64/libtrf.dll 
          dir

        working-directory: ${{ github.workspace }}

  ubuntu_build:
    name: "Ubuntu 20.04 Build"
    runs-on: ubuntu-20.04    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Print Release Version
        run: |
          echo "Backend Release ${{ github.event.inputs.S1000ReleaseTag }}"
          echo "Frontend Release ${{ github.event.inputs.S1000ReleaseTag }}"

   
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLIENT_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CLIENT_SECRET }}
          aws-region: us-east-2

      - name: Retrieve libtrf Repository from s3
        run: |
          aws s3 cp s3://thinkrf-component-libtrf-library/${{ github.event.inputs.LibtrfReleaseTag }}/libtrf.h 
          aws s3 cp s3://thinkrf-component-libtrf-library/${{ github.event.inputs.LibtrfReleaseTag }}/linux/x86_64/libtrf.so 
          dir
        working-directory: ${{ github.workspace }}