name: S1000 Frontend Pipeline

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'The s1000 frontend tag that you would like to create a release. Ex: 1.3.0'     
        required: true    
      appEnv:
        description: 'App Environment: options (test)'     
        required: True        

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Parse App Name
      run: |  
        if [ ${{ github.event.inputs.appEnv }} == "dev" ]; then echo "APP_NAME=DevS1000" >> $GITHUB_ENV; fi 
        if [ ${{ github.event.inputs.appEnv }} == "test" ]; then echo "APP_NAME=TestS1000" >> $GITHUB_ENV; fi
        if [ ${{ github.event.inputs.appEnv }} == "prod" ]; then echo "APP_NAME=ProdS1000" >> $GITHUB_ENV; fi

    - name: Install Bitbuket SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
        name: id_rsa_bit
        known_hosts: ${{ secrets.KNOWN_HOSTS_BITBUCKET }}
        config: |
          Host bitbucket-git
            HostName bitbucket.org
            IdentityFile ~/.ssh/id_rsa_bit
        if_key_exists: replace

    - name: Install AWS EC2 SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
        name: id_rsa_aws_ec2
        known_hosts: ${{ secrets.KNOWN_HOSTS_AWS_EC2 }}
        config: |
          Host aws-ec2
            HostName ec2-3-143-123-50.us-east-2.compute.amazonaws.com
            IdentityFile ~/.ssh/id_rsa_aws_ec2
        if_key_exists: replace

    # - name: Retrieve Repository
    #   run: |
    #     git clone git@bitbucket-git:thinkrfsoftware/s1000_frontend.git
    #     cd s1000_frontend
    #     git checkout ${{ github.event.inputs.releaseTag }}

    - name: Deploy
      run: |
        ssh ubuntu@aws-ec2
        echo "ls -l" | ssh ubuntu@aws-ec2 /bin/bash
    # - name: Deploy to AWS Elastic Beanstalk
    #   uses: einaregilsson/beanstalk-deploy@v21
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     application_name: ${{ env.APP_NAME }}
    #     environment_name: ${{ env.APP_NAME }}-env
    #     version_label: ${{ github.event.inputs.releaseTag }}
    #     region: us-east-2
    #     deployment_package: s1000_frontend/s1000-${{ github.event.inputs.appEnv }}.zip    